"""Independent Evaluator Agent (QA/Risk Approver) for Trade Proposals.

Taking inspiration from GANs and Anthropic's Harness design, this agent acts
as a critical evaluator that reviews trades proposed by the Generator engine.
It mitigates the AI's "evaluation bias" by being explicitly prompted to be
skeptical and risk-averse.
"""

from __future__ import annotations

import json
from typing import Any, Dict
from src.agentic.llm_router import LLMRouter
from src.execution.models import utc_now_iso

class EvaluatorAgent:
    """Evaluates trading proposals generated by System1 or Planner."""

    def __init__(self, router: LLMRouter = None):
        self.router = router or LLMRouter()

    def evaluate_trade(
        self,
        proposal: Dict[str, Any],
        portfolio_state: Dict[str, Any],
        market_context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Critically evaluates a trade proposal.
        Returns a decision dict with 'approved' (bool) and 'reason' (str).
        """
        # We only evaluate actual buy/sell actions, holds are implicitly approved to save tokens
        action = proposal.get("action", 1)
        if action == 1:
            return {"approved": True, "reason": "Hold action requires no secondary approval."}

        action_str = "BUY" if action == 2 else "SELL"
        
        prompt = f"""
You are the Chief Risk Officer (Evaluator Agent) of an Autonomous Trading Company.
Your ONLY job is to prevent the Generator (the trading algorithm) from making stupid, risky, or hallucinated trades.
You are naturally skeptical. You do not trust the Generator. You look for reasons to REJECT the trade.

[PROPOSED TRADE]
Action: {action_str}
Asset: {proposal.get("symbol")}
Confidence/Signal: {proposal.get("signal_strength")}

[CURRENT PORTFOLIO STATE]
Realized PnL: {portfolio_state.get("realized_pnl", 0.0):.4f}
Day PnL: {portfolio_state.get("day_pnl", 0.0):.4f}
Current Position: {portfolio_state.get("current_position", 0.0):.4f}

[MARKET CONTEXT]
Volatility: {market_context.get("volatility", 0.0):.4f}

EVALUATION CRITERIA:
1. Is the Day PnL already deeply negative? If so, REJECT buying more (loss aversion).
2. Is the volatility exceptionally high? If so, REJECT aggressive large positions.
3. Does this trade seem like an over-reaction to a minor signal?

Output ONLY a JSON object matching this schema:
{{
    "approved": boolean,
    "reason": "A strict 1-sentence justification of your decision, pointing out any specific risks."
}}
"""
        
        try:
            # We use Anthropic or OpenAI as preference for evaluation to avoid Gemini's self-bias if Gemini generated the proposal
            text = self.router.generate_content(prompt, temperature=0.0, preferred_provider="openai")
            
            if not text:
                return {"approved": False, "reason": "Evaluator LLM failed to respond. Failsafe: Reject."}

            if text.startswith("```json"):
                text = text[7:]
            if text.endswith("```"):
                text = text[:-3]
                
            result = json.loads(text.strip())
            return {
                "approved": bool(result.get("approved", False)),
                "reason": result.get("reason", "No reason provided by Evaluator.")
            }
        except Exception as e:
            return {
                "approved": False, 
                "reason": f"Evaluator encountered an error: {str(e)}. Failsafe: Reject."
            }
