"""Independent Evaluator Agent (QA/Risk Approver) for Trade Proposals.

Taking inspiration from GANs and Anthropic's Harness design, this agent acts
as a critical evaluator that reviews trades proposed by the Generator engine.
It leverages the Company SOUL (SOUL.md) and available Skills for validation.
"""

from __future__ import annotations
import json
import os
from typing import Any, Dict, List
from pathlib import Path
from src.agentic.llm_router import LLMRouter
from src.agentic.skill_manager import SkillManager
from src.execution.models import utc_now_iso

class EvaluatorAgent:
    """Evaluates trading proposals generated by System1 or Planner based on Company SOUL."""

    def __init__(self, router: LLMRouter = None, skill_manager: SkillManager = None):
        self.router = router or LLMRouter()
        self.skill_manager = skill_manager or SkillManager()
        self.soul_path = Path("configs/SOUL.md")
        self.soul_content = self._load_soul()

    def _load_soul(self) -> str:
        """Loads the company's core mission and risk philosophy."""
        if self.soul_path.exists():
            return self.soul_path.read_text(encoding="utf-8")
        return "Conservative risk management and autonomous growth."

    def evaluate_trade(
        self,
        proposal: Dict[str, Any],
        portfolio_state: Dict[str, Any],
        market_context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Critically evaluates a trade proposal using SOUL.md and available skills.
        Returns a decision dict with 'approved' (bool) and 'reason' (str).
        """
        # Holds are implicitly approved to save tokens and avoid unnecessary friction
        action = proposal.get("action", 1)
        if action == 1:
            return {"approved": True, "reason": "Hold action is low risk", "critical_finding": None}

        # Prepare available skills info for the AI
        skills_info = json.dumps(self.skill_manager.get_tool_definitions(), indent=2, ensure_ascii=False)

        system_prompt = f"""
당신은 'Autonomous Company'의 최고 리스크 책임자(CRO)입니다.
아래의 [COMPANY SOUL] 원칙을 최우선으로 준수하여 거래 제안을 검토하십시오.

[COMPANY SOUL]
{self.soul_content}

당신은 필요시 다음의 [AVAILABLE SKILLS]를 활용하여 추가 지표를 계산할 것을 제안할 수 있습니다:
{skills_info}

[평가 지침]
1. 제안이 회사의 철학과 리스크 관리 기준에 부합하는가?
2. 시장 상황 대비 제안된 수량과 방향이 적절한가?
3. 자가 합리화(Self-bias)를 경계하고, 조금이라도 의심스러우면 '반려(Reject)'하십시오.

반드시 JSON 형식으로만 응답하십시오:
{{
  "approved": boolean,
  "reason": "검토 근거 요약 (SOUL.md 원칙 인용 권장)",
  "critical_finding": "발견된 잠재적 위험 요소 (없으면 null)",
  "requested_skill": "추가 검증을 위해 실행이 필요한 스킬 ID (없으면 null)"
}}
"""
        user_prompt = f"""
[Current Proposal]
{json.dumps(proposal, indent=2)}

[Portfolio State]
{json.dumps(portfolio_state, indent=2)}

[Market Context]
{json.dumps(market_context, indent=2)}

Timestamp: {utc_now_iso()}
Evaluate this proposal now.
"""
        try:
            # We prefer OpenAI/Anthropic for evaluation to avoid Gemini's self-bias if it was the generator
            res_text = self.router.generate_content(
                prompt=user_prompt,
                system_instruction=system_prompt,
                preferred_provider="openai"
            )
            
            # Simple JSON extraction from response
            start = res_text.find("{")
            end = res_text.rfind("}") + 1
            if start != -1 and end != -1:
                return json.loads(res_text[start:end])
            
            return {"approved": False, "reason": "Failed to parse AI response as JSON", "critical_finding": res_text}
        except Exception as e:
            return {"approved": False, "reason": f"Evaluation error: {str(e)}", "critical_finding": None}
